version: "3.9"
services:
  postgres:
    image: "postgres:12.9"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "/home/evgeniy/test/sql/data:/var/lib/postgresql/data/pgdata"
      - "/home/evgeniy/test/sql/backup:/var/lib/postgresql/data"
    ports:
      - "5432:5432"