---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elastic-role

  - src: git@github.com:evgenfomin/kibana-role.git
    scm: git
    version: "1.0.0"
    name: kibana-role

  - src: git@github.com:evgenfomin/filebeat-role.git
    scm: git
    version: "1.0.0"
    name: filebeat-role